@baseUrl = http://localhost:3001

### Create user in dev (DB = noteApp)
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "username": "tester",
  "name": "Test User",
  "password": "sekret"
}