GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info
Accept: application/json

###
GET http://localhost:3001/api/persons/000000000000000000000000

###
GET http://localhost:3001/api/persons/bad-id
